// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfqSLpJ3vWk7QitiAyxoNohzI4okSGcR4',
    appId: '1:290789299158:web:7c347bfe629578fa978a77',
    messagingSenderId: '290789299158',
    projectId: 'messaging-f8ed7',
    authDomain: 'messaging-f8ed7.firebaseapp.com',
    storageBucket: 'messaging-f8ed7.firebasestorage.app',
    measurementId: 'G-WYMYR2RZ5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz3vREHTpSg7JritXldkMTPAi7qdh1Joo',
    appId: '1:290789299158:android:243118d4f23bc2f8978a77',
    messagingSenderId: '290789299158',
    projectId: 'messaging-f8ed7',
    storageBucket: 'messaging-f8ed7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD49r0BWi1vRuyNJ1O77xAdV0KUu_5LKAU',
    appId: '1:290789299158:ios:8fad763cc3cbf8b8978a77',
    messagingSenderId: '290789299158',
    projectId: 'messaging-f8ed7',
    storageBucket: 'messaging-f8ed7.firebasestorage.app',
    iosBundleId: 'com.example.alert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD49r0BWi1vRuyNJ1O77xAdV0KUu_5LKAU',
    appId: '1:290789299158:ios:8fad763cc3cbf8b8978a77',
    messagingSenderId: '290789299158',
    projectId: 'messaging-f8ed7',
    storageBucket: 'messaging-f8ed7.firebasestorage.app',
    iosBundleId: 'com.example.alert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfqSLpJ3vWk7QitiAyxoNohzI4okSGcR4',
    appId: '1:290789299158:web:cae8f969a645354c978a77',
    messagingSenderId: '290789299158',
    projectId: 'messaging-f8ed7',
    authDomain: 'messaging-f8ed7.firebaseapp.com',
    storageBucket: 'messaging-f8ed7.firebasestorage.app',
    measurementId: 'G-8EJ6ZRJCC9',
  );
}
